version: "3"
services:
  frontend:
    build: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "3001:3001"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

